server:
  port: 8888

spring:
  application:
    name: Gateway
  cloud:
    discovery:
      enabled: true
      # Utilisez Consul au lieu d'Eureka
      consul:
        enabled: true
        host: localhost
        port: 8500

#eureka:
 # instance:
  #  hostname: gateway
   # prefer-ip-address: true
  #client:
   # fetch-registry: true
    #register-with-eureka: true
    #service-url:
     #  defaultZone: http://eurekaserver:8761/eureka
# Configuration Consul
